@baseUrl = {{$dotenv HA_BASE_URL}}
@token = {{$dotenv HA_TOKEN}}
@entityId = {{$dotenv HA_LIGHT_ENTITY_ID}}


### 获取灯光状态
GET {{baseUrl}}/api/states/{{entityId}}
Authorization: Bearer {{token}}
Content-Type: application/json


### 开灯
POST {{baseUrl}}/api/services/light/turn_on
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "entity_id": "{{entityId}}"
}

### 关灯
POST {{baseUrl}}/api/services/light/turn_off
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "entity_id": "{{entityId}}"
}

### 控制色温
POST {{baseUrl}}/api/services/light/turn_on
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "entity_id": "{{entityId}}",
  "color_temp": 100
}

### 控制色温(开尔文单位)
POST {{baseUrl}}/api/services/light/turn_on
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "entity_id": "{{entityId}}",
  "color_temp_kelvin": 2700
}

### 控制亮度
POST {{baseUrl}}/api/services/light/turn_on
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "entity_id": "{{entityId}}",
  "brightness": 10
}
